#!/bin/bash
# Note that the lines with $ are the qsub flags
# Execute from the current working directory
#$ -cwd
#
#  We want to use 1 gpu
#$ -l gpus=1
#  Memory
#$ -l vf=2G
# If you want to get e-mail notification you can do the following
#$ -m aes
 
python download_tweets.py tweeti-b.dist.tsv >> downloaded_tweets.tsv
 
# Run command 2python3 sentimentLabeler.py --data .. --embedding "both" --device cuda --restore both_5_weights.pt
